### ISSUE TITLE
preperencePane manager don't respect `src` in options

### ISSUE THREAD

**Issue by aidenlx** [windingwind/zotero-plugin-toolkit#11]
It seems that in Zotero 6 compat code, the url is still hard-coded

https://github.com/windingwind/zotero-plugin-toolkit/blob/1299bf62c69077b9056345c971327ceea3753aca/src/managers/preferencePane.ts#L217-L220

**Comment by windingwind** [comment]
Yes it is. Considering that Z6’s lifetime is going to an end this year, this is a reasonable workaround.
