### ISSUE TITLE
In preferencepanemanager.register, where does ZoteroCompat come from?

### ISSUE THREAD

**Issue by retorquere** [windingwind/zotero-plugin-toolkit#13]
In [preferencepanemanager.register](https://github.com/windingwind/zotero-plugin-toolkit/blob/master/docs/zotero-plugin-toolkit.preferencepanemanager.register.md), where does `ZoteroCompat` come from?

**Comment by windingwind** [comment]
My bad. The docs are outdated.

The compat is now part of basic tool class.

See plugin template repo for examples of the latest version.

**Comment by retorquere** [comment]
Where does `ztoolkit` come from in https://github.com/windingwind/zotero-plugin-template/blob/576c08b5cf83ff7d69da31e7b16cc4b122dac0be/src/modules/examples.ts?

**Comment by volatile-static** [comment]
> Where does `ztoolkit` come from in https://github.com/windingwind/zotero-plugin-template/blob/576c08b5cf83ff7d69da31e7b16cc4b122dac0be/src/modules/examples.ts?

https://github.com/windingwind/zotero-plugin-template/blob/576c08b5cf83ff7d69da31e7b16cc4b122dac0be/src/index.ts#L15

https://github.com/windingwind/zotero-plugin-template/blob/576c08b5cf83ff7d69da31e7b16cc4b122dac0be/typing/global.d.ts#L13

**Comment by windingwind** [comment]
The docs are updated.
