### ISSUE TITLE
How can I access the metadata/file paths of all a users's saved files?

### ISSUE THREAD

**Issue by ShreyJ1729** [windingwind/zotero-plugin-toolkit#25]
New user of the library here. I was looking through the docs and couldn't find anything on this. How can I access a user's saved items? I'm building a tool that backs up data in a private cloud so I want to get a list of all the metadata of the users items and push them to my DB.

**Comment by windingwind** [comment]
The APIs of data: https://github.com/windingwind/zotero-types/blob/master/types/xpcom/data/items.d.ts

The source code of Zotero: https://github.com/zotero/zotero/blob/main/chrome/content/zotero/xpcom/data/items.js

**Comment by ShreyJ1729** [comment]
Thanks! Quick second question - how can I access the logged in user's email address?

**Comment by windingwind** [comment]
`Zotero.Prefs.get("sync.server.username")`
Please ask the user for permission before getting this sensitive information.
