### ISSUE TITLE
[DevBug] 单独注册itemBox的row，不显示

### ISSUE THREAD

**Issue by RayKr** [windingwind/zotero-plugin-toolkit#32]
问题描述：
使用`ztoolkit.ItemBox.register`单独注册一个info row的时候是不显示的，查看log，是由于globalCache为undefined导致。
![CleanShot 2023-09-09 at 11 29 39@2x](https://github.com/windingwind/zotero-plugin-toolkit/assets/10293675/64ab9a60-1df8-4741-ac5c-bbd4387230e6)

**Comment by RayKr** [comment]
貌似是由于在初始化的时候用了个连续赋值，连续赋值有坑，参见[这里](https://blog.csdn.net/weixin_42498253/article/details/121643254)
![CleanShot 2023-09-09 at 11 45 49@2x](https://github.com/windingwind/zotero-plugin-toolkit/assets/10293675/c37cc2c2-7acd-4b5c-a682-47894586254d)
对于this.globalCache的赋值单独一行，就正常了
<img width="687" alt="image" src="https://github.com/windingwind/zotero-plugin-toolkit/assets/10293675/b406767c-36b9-48dd-92d7-c0c4c49483ad">

**Comment by RayKr** [comment]
#33

**Comment by windingwind** [comment]
感谢。这部分的api即将由正式的zotero内实现替代，见https://github.com/zotero/zotero/pull/3255

**Comment by RayKr** [comment]
风大👍
