### ISSUE TITLE
Redundant logs in Zotero console

### ISSUE THREAD

**Issue by ChenglongMa** [windingwind/zotero-plugin-toolkit#41]
你好，

首先，十分感谢对该toolkit的开发，极大地缩短了插件的开发周期！

不知道是不是我设置的不对，不管我把 `process.env.NODE_ENV` 设置为`development` 还是 `production`，我都会在Zotero的Console中看到以下log：

![bug](https://github.com/windingwind/zotero-plugin-toolkit/assets/33501679/77369345-a05b-423c-8a55-5daeecdda923)

请问如何屏蔽到这些？

另外打包时，无论有没有用到，都会将该toolkit中全部的代码都打包在内吗？

谢谢！

**Comment by northword** [comment]
前者 bug，待修复。

后者需要自行创建类，按需引入，见模板仓库 `src/utils/ztoolkit.ts`，或

https://github.com/northword/zotero-format-metadata/blob/e7966a6b4d59238699303011ccf21ce25b579621/src/utils/ztoolkit.ts#L39-L59

**Comment by northword** [comment]
另外，图中的日志是 prompt 的，取消导入这个应该就没了。新建 dialog 时候的 element dom 在 prod 也打印了应该是 bug。

**Comment by northword** [comment]
这里有一个 Zotero 插件开发者的交流群，如果你有兴趣，可以加群一起讨论～

![Screenshot_2024-01-12-20-47-57-292_com.tencent.mm.jpg](https://github.com/windingwind/zotero-plugin-toolkit/assets/44738481/368740a9-48f0-4819-9374-f4f700ab0633)

**Comment by ChenglongMa** [comment]
非常感谢！已经进群了 :)
