### ISSUE TITLE
Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

### ISSUE THREAD

**Issue by zzlb0224** [windingwind/zotero-plugin-toolkit#50]
Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead

**Comment by windingwind** [comment]
It's from

https://github.com/windingwind/zotero-plugin-toolkit/blob/35dc0b0b36961f3befc1fd6014f75a9ccba84187/src/managers/preferencePane.ts#L224

, which is deprecated:

https://github.com/windingwind/zotero-plugin-toolkit/blob/35dc0b0b36961f3befc1fd6014f75a9ccba84187/src/managers/preferencePane.ts#L7
