### ISSUE TITLE
[BUG] `window` can be `null` when calling `Zotero.getMainWindow()`

### ISSUE THREAD

**Issue by ChenglongMa** [windingwind/zotero-plugin-toolkit#57]
https://github.com/windingwind/zotero-plugin-toolkit/blob/a6a90697788a10a3f11e22372dceef7ba076cf70/src/basic.ts#L120-L130

**L129** may return `null` when the main window has been unloaded.

It will cause a `Type Error` in the invoker, e.g., `ztoolkit.log()`.

**Comment by windingwind** [comment]
Thanks for the feedback.
