### ISSUE TITLE
Add paste functionality to ClipboardHelper

### ISSUE THREAD

**Issue by lesstech** [windingwind/zotero-plugin-toolkit#59]
It would be great, if the clipboard helper could also support paste functionality!

**Comment by windingwind** [comment]
You mean read the clipboard?

**Comment by lesstech** [comment]
Yes, I mean read the clipboard.
Sorry, english isn't my first language.

**Comment by windingwind** [comment]
`Zotero.Utilities.Internal.getClipboard("text/plain")`
