### ISSUE TITLE
Get selected text in library tab?

### ISSUE THREAD

**Issue by ImperialSquid** [windingwind/zotero-plugin-toolkit#60]
Getting the selected text in a reader tab is relatively simple, I was wondering if it's possible to get the selected text in the library tab too (eg if the user has selected some text in a note)

I didn't see anything like that in this toolkit, and a skim of the main Zotero repo didn't show anything, but I might have missed it. 

Thanks in advance!

**Comment by windingwind** [comment]
Note editor is in an iframe and thus getting the selection can be complicated. What do you plan to do with the selection in note editor?

**Comment by windingwind** [comment]
I'm not familiar with the accessibility issues, but I guess Zotero has support for screen readers. For me, the MacOS VoiceOver can read the selection in the note as expected.

Back to your question, try this:

```js
if (ZoteroPane.itemPane.mode === "note") {
    Zotero.debug(ZoteroPane.itemPane.getCurrentPane()._iframe.contentDocument.getSelection());
}
```

**Comment by ImperialSquid** [comment]
I was making a joke about my continued [struggles with highlighting text within the reader iframe](https://groups.google.com/g/zotero-dev/c/lj_thX_5P2Y), sorry for any confusion...!

For the solution, that works perfectly, thanks! Looks like there's some variation in terms of what fields exist on what types, but this definitely helps point me in the right direction!
