### ISSUE TITLE
globalCache is undefined

### ISSUE THREAD

**Issue by Dominic-DallOsto** [windingwind/zotero-plugin-toolkit#64]
Hi, I recently had this issue (https://github.com/Dominic-DallOsto/zotero-reading-list/issues/58) where my plugin is unable to startup with the error: `globalCache is undefined`. It seems this only happens when multiple plugins are installed that use zotero-plugin-toolkit, and disabling all other plugins solves the problem.

Please see these issues for more details:
* https://github.com/Dominic-DallOsto/zotero-reading-list/issues/58
* https://github.com/github-young/zotero-better-authors/issues/77
* https://github.com/daeh/zotero-markdb-connect/issues/138

Could it be that having multiple instances of zotero-plugin-toolkit running somehow causes conflicts?

**Comment by northword** [comment]
Bump the version of toolkit to v4.

**Comment by Dominic-DallOsto** [comment]
Perfect, thanks a lot! This seems to have solved the issue!
