### ISSUE TITLE
tree shaking - @v4

### ISSUE THREAD

**Issue by volatile-static** [windingwind/zotero-plugin-toolkit#65]
升级到4.0.0（#63 ）之后，似乎不能完美实现**按需导入**。
![image](https://github.com/user-attachments/assets/caf6f8f9-3657-4642-bff8-40823035ffee)
比如上图中可以看到`ProgressWindowHelper`在整个仓库中只出现了一次，而且会提示“未使用的变量名”，不理解是怎么被bundle进来的。
本来只是个小问题，但巧的是它直接继承了`Zotero.ProgressWindow`类，导致任何不在插件环境下的代码都会在load时报错。
同时，后来补充的wait（ dad043e1ff1ae7def91d919e8957ac6d353d34dd ）也会在只使用一个函数的情况下打包整个文件：
![image](https://github.com/user-attachments/assets/8b12f3db-b11c-4236-a4c6-8eaeed3ac583)
@northword

**Comment by northword** [comment]
wait 是因为导出用了别名的问题，index.ts 里应该写为 `export * form "./utils/wait.js"` 的，或者就是按路径导出，在 package.json 里写为

```json
{
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js"
    },
    "./wait": {
      "types": "./dist/utils/wait.d.ts",
      "import": "./dist/utils/wait.js"
    }
  },
}
```

这属于 esbuild 的问题，如果用 rollup 这种打包器，应该是可以的：https://github.com/evanw/esbuild/issues/1420 。这个当时在群里提到过，你说这个文件不大没影响，我就没去改。

---

前一个 progressWindow 的问题，我调查一下。

**Comment by volatile-static** [comment]
没关系，我提到wait的问题只是想方便你排查progressWindow的问题

**Comment by northword** [comment]
processWindow 的问题，我怀疑是 BasicTool.debug -> hint -> ProgressWindowHelper 导致的

https://github.com/windingwind/zotero-plugin-toolkit/blob/bc6585713f5cfb3090408c4aefd26407e1375d06/src/basic.ts#L36

https://github.com/windingwind/zotero-plugin-toolkit/blob/bc6585713f5cfb3090408c4aefd26407e1375d06/src/utils/pluginBridge.ts#L90

**Comment by volatile-static** [comment]
不是吧，hint函数里用到的不是toolkit继承后的progresswindow

**Comment by northword** [comment]
progressWindowHelper 的问题会不会和这个类似？

https://github.com/evanw/esbuild/issues/1912: gets included because of non existent class in extends

**Comment by volatile-static** [comment]
是的，我把extends去掉之后就shake掉了，可以认为对esbuild来说这是个无解的问题。因为 #66 缓解了progresswindow问题，这个可以先关掉，之后有希望再考虑

**Comment by northword** [comment]
我再次发现了这个问题（类似 progressWindow 这个），具体如下：

由于 ZoteroToolkit 中使用了 GuideHelper，导致即使用户没有使用 ZoteroToolkit 和 GuideHelper ，这两个类仍会被打包进去。

我目前认为这有两部分原因构成：

1. 我们不应该同时导出一个使用了其他模块的 ZoteroToolkit，这会导致循环引用，导致 bundler 无法识别未使用的模块，阻碍 tree-shaking
    - 使用 unbundle 模式可以缓解此问题 
2. esbuild 在 tree-shaking 上存在缺陷（即 https://github.com/evanw/esbuild/issues/1912 ），当按第一点中提到的使用 unbundle 模式时（也就是按 #98 修改后），esbuild 仍不能正常 tree-shaking，而 rolldown 可以。


所以为了解决这个问题，我们应该：

1. 在 toolkit 中，使用 undundle 模式 （https://github.com/windingwind/zotero-plugin-toolkit/pull/98 ），或是把 ZoteroToolkit 从其他地方导出去
2. 在 scaffold 中，弃用 esbuild，集成 rolldown 或其他打包器

**Comment by windingwind** [comment]
可以考虑去掉`ZoteroToolkit`，改为在template仓库里创建并引用
